[workspace]
members = ["macros"]

[package]
name = "bitmap"
version = "0.1.0"
edition = "2024"

[dependencies]
macros = { path = "./macros" }

[dev-dependencies]
trybuild = "1.0.111"
paste = "1.0.15"
